app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::get('/', function(){
    if(Auth::check())
        return Redirect::to('/admin');
    else
        return Redirect::to('/login');
});

// Client
Route::any('/quotes/quote/{id}', 'QuotesController@quote');

// Admin login
Route::get('login', 'AuthController@index');
Route::post('login', 'AuthController@login');
Route::get('logout', 'AuthController@logout');

// Admin
Route::group(array('before' => 'auth'), function(){
    Route::group(array('prefix' => 'admin'), function(){
        Route::get('/', 'Admin\DashboardController@index');
        Route::post('/', 'Admin\DashboardController@history');
        Route::resource('/clients', 'Admin\ClientsController');
        Route::get('/quotes/mail/{id}', [
            'uses' => 'Admin\MailQuoteController@preview',
            'as'   => 'admin..quotes.mail'
        ]);
        Route::post('/quotes/mail/{id}', [
            'uses' => 'Admin\MailQuoteController@send',
            'as'   => 'admin..quotes.mail'
        ]);    Route::resource('/quotes', 'Admin\QuotesController');
        Route::get('/transactions', 'Admin\TransactionsController@index');
        Route::post('/import/quote', [
        	'uses' => 'Admin\ImportController@quote',
            'as' => 'admin..import.quote'
        ]);
        Route::get('/export', 'Admin\ExportController@index');
    });
});


// IPNs
Route::group(array('prefix' => 'ipn'), function(){
    Route::any('/webpay', 'IPN\WebpayController@notification');
});

app/models/Client.php
<?php

use Illuminate\Database\Eloquent\ModelNotFoundException;

class Client extends Eloquent{
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'clients';

	public function quotes(){
		return $this->hasMany('Quote');
	}

	public function transactions(){
		return $this->hasManyThrough('Transaction', 'Quote');
	}

	public function getFullnameAttribute(){
		return $this->name . ' ' . $this->surname;
	}
	public function setPasswordAttribute($password) {
		$this->attributes['password'] = Hash::make($password);
	}
	public static function findByRut($rut){
		return self::where('rut', $rut)->first();
	}
}

app/controllers/admin/ClientsController.php
<?php
namespace Admin;

use Client;

use Validator, Input, Redirect, Session, Lang;

use Illuminate\Support\Facades\View;

use AdminController;
class ClientsController extends AdminController{
	public function index(){
		$clients = Client::all();
		return View::make('admin.clients.index', compact('clients'));
	}
	public function create(){
		return View::make('admin.clients.create');
	}
	public function store(){
        $validator = Validator::make(Input::all(), array(
            'name'			=> 'required',
            'surname'		=> 'required',
            'rut'			=> 'required|unique:clients',
            'email'			=> 'required|email|unique:clients',
            'password'		=> 'required'
        ));

        if ($validator->fails()) {
            return Redirect::to('admin/clients/create')
                ->withErrors($validator)
                ->withInput(Input::except('password'));
        }
        else {
            $client = new Client;
            $client->name 		= Input::get('name');
            $client->surname	= Input::get('surname');
            $client->rut		= Input::get('rut');
            $client->email		= Input::get('email');
            $client->password	= Input::get('password');
            $client->save();

            Session::flash('success_message', Lang::get('clients.store.success'));

            return Redirect::to('admin/clients');
        }
	}
        	public function show($id){
        $client = Client::findOrFail($id);

        return View::make('admin.clients.show', compact('client'));
    }
	public function edit($id){
        $client = Client::findOrFail($id);

        return View::make('admin.clients.edit', compact('client'));
    }
    public function update($id){
        $client = Client::findOrFail($id);

        $validator = Validator::make(Input::all(), array(
            'name'          => 'required',
            'surname'       => 'required',
            'rut'           => "required|unique:clients,rut,{$id}",
            'email'         => "required|email|unique:clients,email,{$id}",
            'password'      => 'required'
        ));

        if ($validator->fails()) {
            return Redirect::to("admin/clients/{$id}/edit")
                ->withErrors($validator)
                ->withInput(Input::except('password'));
        }
        else {
            $client->name       = Input::get('name');
            $client->surname    = Input::get('surname');
            $client->rut        = Input::get('rut');
            $client->email      = Input::get('email');
            $client->password   = Input::get('password');
            $client->save();

            Session::flash('success_message', Lang::get('clients.store.success'));

            return Redirect::to("admin/clients/{$id}/edit");
        }
    }
    public function destroy($id){
        $client = Client::findOrFail($id);
        $client->delete();

        Session::flash('success_message', Lang::get('clients.destroy.success'));

        return Redirect::to('admin/clients');
    }
}

app/views/admin/clients/create.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
	<div class="span12">
		<div class="widget">
			<div class="widget-header"> <i class="icon-th-list"></i>
				<h3>@lang('clients.clients')</h3>
			</div>
			<div class="widget-content">
				{{ Form::open(array('url' => 'admin/clients', 'class' => 'form-horizontal')) }}
					<fieldset>
						<div class="control-group">
							{{ Form::label('name', trans('clients.name'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('name', Input::old('name'), array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('surname', trans('clients.surname'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('surname', Input::old('surname'), array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('rut', trans('clients.rut'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('rut', Input::old('rut'), array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('email', trans('clients.email'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('email', Input::old('email'), array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('password', trans('clients.password'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('password', Input::old('password'), array('class' => 'span6')) }}
							</div>
						</div>
						<div class="form-actions">
							<button type="submit" class="btn btn-primary">@lang('form.button.save')</button> 
							<button class="btn">@lang('form.button.cancel')</button>
						</div>
					</fieldset>
				{{ Form::close() }}
			</div>
		</div>
	</div>
</div>
@stop

app/views/admin/clients/edit.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
	<div class="span12">
		<div class="widget">
			<div class="widget-header"> <i class="icon-th-list"></i>
				<h3>{{ $client->fullname }}</h3>
				<a href="{{ url("admin/clients", $client->id) }}" class="btn btn-mini btn-default">@lang('form.button.show')</a>
			</div>
			<div class="widget-content">
				{{ Form::model($client, array('route' => array('admin..clients.update', $client->id), 'method' => 'PUT')) }}
					<fieldset>
						<div class="control-group">
							{{ Form::label('name', trans('clients.name'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('name', null, array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('surname', trans('clients.surname'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('surname', null, array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('rut', trans('clients.rut'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('rut', null, array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('email', trans('clients.email'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('email', null, array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('password', trans('clients.password'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('password', null, array('class' => 'span6')) }}
							</div>
						</div>
						<div class="form-actions">
							<button type="submit" class="btn btn-primary">@lang('form.button.save')</button> 
							<button class="btn">@lang('form.button.cancel')</button>
						</div>
					</fieldset>
				{{ Form::close() }}
			</div>
		</div>
	</div>
</div>
@stop

app/views/admin/clients/index.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
	<div class="span12">
		<div class="widget widget-table action-table">
			<div class="widget-header">
				<i class="icon-th-list"></i>
				<h3>@lang('clients.clients')</h3>
				<!--<a href="{{ url('admin/clients/create') }}" class="btn btn-mini btn-default">Agregar</a>-->
			</div>
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>@lang('clients.id')</th>
							<th>@lang('clients.fullname')</th>
							<th>@lang('clients.email')</th>
							<th>@lang('clients.rut')</th>
							<th>@lang('clients.created_at')</th>
							<!--<th></th>-->
						</tr>
					</thead>
					<tbody>
						@foreach($clients as $client)
						<tr>
							<td><a href="{{ URL::route('admin..clients.show', $client->id) }}">{{ $client->id }}</a></td>
							<td><a href="{{ URL::route('admin..clients.show', $client->id) }}">{{ $client->fullname }}</a></td>
							<td>{{ $client->email }}</td>
							<td>{{ $client->rut }}</td>
							<td>{{ $client->created_at }}</td>
							<!--<td>
								<a href="{{ url("admin/clients/{$client->id}/edit") }}" class="btn btn-mini btn-success pull-left">@lang('form.button.edit') <i class="btn-icon-only icon-ok"> </i></a>
							    {{ Form::open(array('url' => array('admin/clients', $client->id), 'method' => 'delete', 'class' => 'pull-left', 'style' => 'margin: 0 0 0 5px')) }}
								<buttom type="submit" class="btn btn-danger btn-mini">@lang('form.button.remove') <i class="btn-icon-only icon-remove"> </i></button>
								{{ Form::close() }}
							</td>-->
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>	
	</div>
</div>
@stop

app/views/admin/clients/show.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
	<div class="span5">
		<div class="widget widget-table action-table">
			<div class="widget-header"> <i class="icon-th-list"></i>
				<h3>{{ $client->fullname }}</h3>
				<!--<a href="{{ url("admin/clients/{$client->id}/edit") }}" class="btn btn-mini btn-default">@lang('form.button.edit')</a>-->
			</div>
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<tr>
						<td>@lang('clients.name')</td>
						<td>{{ $client->name }}</td>
					</tr>
					<tr>
						<td>@lang('clients.surname')</td>
						<td>{{ $client->surname }}</td>
					</tr>
					<tr>
						<td>@lang('clients.rut')</td>
						<td>{{ $client->rut }}</td>
					</tr>
					<tr>
						<td>@lang('clients.email')</td>
						<td>{{ $client->email }}</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="widget widget-table action-table">
			<div class="widget-header">
				<i class="icon-th-list"></i>
				<h3>@lang('transactions.last')</h3>
			</div>
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<thead>
						<th>@lang('transactions.id')</th>
						<th>@lang('transactions.quote')</th>
						<th>@lang('transactions.date')</th>
						<th>@lang('transactions.gateway')</th>
						<th>@lang('transactions.amount')</th>
					</thead>
					<tbody>
						@foreach($client->transactions->take(10) as $transaction)
						<tr>
							<td>{{ $transaction->id }}</td>
							<td>{{ $transaction->quote->name }}</td>
							<td>{{ $transaction->paid_at }}</td>
							<td>{{ $transaction->gateway }}</td>
							<td>{{ $transaction->amount }}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="span7">
		<div class="widget widget-nopad">
			<div class="widget-header"> <i class="icon-list-alt"></i>
				<h3>@lang('quotes.quotes')</h3>
				<span class="label label-info">@lang('quotes.sent')</span>
				<span class="label label-success">@lang('quotes.paid')</span>
			</div>
            <div class="widget-content">
				<div id="calendar"></div>
            </div>
		</div>
	</div>
</div>
@stop
@section('footer')
<script type="text/javascript">
	$(document).ready(function(){
		events = new Array;

		calendar = $('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'	
			},
			selectable: true,
			eventSources: [events]
		});
		@foreach($client->quotes as $quote)
		events.push({
			title: '({{ $quote->id }}) {{ $quote->name }}',
			start: '{{ $quote->sent_at }}',
			allDay: false
        });
		@if($quote->paid_at)
		events.push({
			title: '({{ $quote->id }}) {{ $quote->name }}',
			start: '{{ $quote->paid_at }}',
			color: '#00bb00',
			allDay: false
        });
        @endif
        @endforeach

		calendar.fullCalendar('refetchEvents');
	});
</script>
@stop