app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::get('/', function(){
    if(Auth::check())
        return Redirect::to('/admin');
    else
        return Redirect::to('/login');
});

// Client
Route::any('/quotes/quote/{id}', 'QuotesController@quote');

// Admin login
Route::get('login', 'AuthController@index');
Route::post('login', 'AuthController@login');
Route::get('logout', 'AuthController@logout');

// Admin
Route::group(array('before' => 'auth'), function(){
    Route::group(array('prefix' => 'admin'), function(){
        Route::get('/', 'Admin\DashboardController@index');
        Route::post('/', 'Admin\DashboardController@history');
        Route::resource('/clients', 'Admin\ClientsController');
        Route::get('/quotes/mail/{id}', [
            'uses' => 'Admin\MailQuoteController@preview',
            'as'   => 'admin..quotes.mail'
        ]);
        Route::post('/quotes/mail/{id}', [
            'uses' => 'Admin\MailQuoteController@send',
            'as'   => 'admin..quotes.mail'
        ]);    Route::resource('/quotes', 'Admin\QuotesController');
        Route::get('/transactions', 'Admin\TransactionsController@index');
        Route::post('/import/quote', [
        	'uses' => 'Admin\ImportController@quote',
            'as' => 'admin..import.quote'
        ]);
        Route::get('/export', 'Admin\ExportController@index');
    });
});


// IPNs
Route::group(array('prefix' => 'ipn'), function(){
    Route::any('/webpay', 'IPN\WebpayController@notification');
});

app/models/Client.php
<?php

use Illuminate\Database\Eloquent\ModelNotFoundException;

class Client extends Eloquent{
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'clients';

	public function quotes(){
		return $this->hasMany('Quote');
	}

	public function transactions(){
		return $this->hasManyThrough('Transaction', 'Quote');
	}

	public function getFullnameAttribute(){
		return $this->name . ' ' . $this->surname;
	}
	public function setPasswordAttribute($password) {
		$this->attributes['password'] = Hash::make($password);
	}
	public static function findByRut($rut){
		return self::where('rut', $rut)->first();
	}
}

app/views/admin/dashboard.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
  <div class="span6">
    <div class="widget widget-nopad">
      <div class="widget-header"> <i class="icon-list-alt"></i>
        <h3>@lang('import.import')</h3>
      </div>
      <div class="widget-content">
        <div class="widget big-stats-container">
          <div class="widget-content">
            <h6 class="bigstats">@lang('import.message')</h6>
            <div id="big_stats" class="cf text-center">
              <form method="post" action="{{ URL::route('admin..import.quote') }}">
                <input style="width:300px" name="quote_id" /><br />
                <button style="width:310px" class="btn btn-default">@lang('import.validate')</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="widget widget-table action-table">
      <div class="widget-header">
        <i class="icon-th-list"></i>
        <h3>@lang('transactions.transactions')</h3>
      </div>
      <div class="widget-content">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>@lang('transactions.id')</th>
              <th>@lang('transactions.quote')</th>
              <th>@lang('transactions.amount')</th>
              <th>@lang('transactions.gateway')</th>
              <th>@lang('transactions.paid_at')</th>
              <th>@lang('transactions.reversed_at')</th>
            </tr>
          </thead>
          <tbody>
            @foreach($transactions as $transaction)
            <tr>
              <td>{{ $transaction->id }}</td>
              <td><a href="{{ URL::route('admin..quotes.show', $transaction->quote_id) }}">{{ $transaction->quote->name }}</a></td>
              <td>{{ $transactions->amount }}</td>
              <td>{{ $transactions->gateway }}</td>
              <td>{{ $transactions->created_at }}</td>
              <td>{{ $transactions->reversed_at }}</td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="span6">
    <div class="widget">
      <div class="widget-content" style="padding:15px">
        <div class="form-group text-center">
          <form method="post" action="" style="margin:0">
            <div class="form-inline">
              <input type="text" id="from" data-date-format="yyyy-m-d" name="from" placeholder="@lang('form.from')" class="form-control" />
              <input type="text" id="to" data-date-format="yyyy-m-d" name="to" placeholder="@lang('form.to')" class="form-control"  />
              <button class="btn btn-default">@lang('quotes.filter')</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="widget widget-table action-table">
      <div class="widget-header">
        <i class="icon-th-list"></i>
        <h3>@lang('quotes.latest_unpaid')</h3>
      </div>
      <div class="widget-content">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>@lang('quotes.id')</th>
              <th>@lang('quotes.name')</th>
              <th>@lang('quotes.client')</th>
              <th>@lang('quotes.created_at')</th>
            </tr>
          </thead>
          <tbody>
            @foreach($unpaid_quotes as $quote)
            <tr>
              <td><a href="{{ URL::route('admin..quotes.show', $quote->id) }}">{{ $quote->id }}</a></td>
              <td><a href="{{ URL::route('admin..quotes.show', $quote->id) }}">{{ $quote->name }}</a></td>
              <td>{{ $quote->client->fullname }}</td>
              <td>{{ $quote->created_at }}</td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
    <div class="widget widget-table action-table">
      <div class="widget-header">
        <i class="icon-th-list"></i>
        <h3>@lang('quotes.latest_paid')</h3>
      </div>
      <div class="widget-content">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>@lang('quotes.id')</th>
              <th>@lang('quotes.name')</th>
              <th>@lang('quotes.client')</th>
              <th>@lang('quotes.created_at')</th>
            </tr>
          </thead>
          <tbody>
            @foreach($paid_quotes as $quote)
            <tr>
              <td><a href="{{ URL::route('admin..quotes.show', $quote->id) }}">{{ $quote->id }}</a></td>
              <td><a href="{{ URL::route('admin..quotes.show', $quote->id) }}">{{ $quote->name }}</a></td>
              <td>{{ $quote->client->fullname }}</td>
              <td>{{ $quote->created_at }}</td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
    <div class="widget">
      <div class="widget-content" style="padding:15px">
        <div class="form-group text-center">
          <div class="form-inline">
            <button class="btn btn-default btn-small"><a href="{{ url('admin/export') }}">@lang('form.button.export')</a></button>
            <button class="btn btn-default btn-small"><a href="">@lang('form.button.refresh')</a></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@stop
@section('footer')
<script type="text/javascript">
$(document).ready(function(){
  $('#from, #to').datepicker();
});
</script>
@stop

app/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{{ Config::get('page.title') }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
{{ HTML::style('/css/bootstrap.css') }}
{{ HTML::style('/css/bootstrap-responsive.css') }}
{{ HTML::style('/css/bootstrap-datepicker.css') }}
{{ HTML::style('/css/font-awesome.css') }}
{{ HTML::style('/css/style.css') }}
{{ HTML::style('/css/pages/dashboard.css') }}
{{ HTML::style('/css/selectize.css') }}
{{ HTML::style('http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600') }}
<!--[if lt IE 9]>
{{ HTML::script('http://html5shim.googlecode.com/svn/trunk/html5.js') }}
<![endif]-->
@yield('header')
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">{{ Config::get('page.name') }}</a>
      <button class="btn btn-default btn-small pull-right"><a href="{{ url('logout') }}">@lang('form.button.logout')</a></button>
    </div>
  </div>
</div>
<div class="subnavbar">
  <div class="subnavbar-inner">
    <div class="container">
      <ul class="mainnav">
        @if(Request::is('admin') or Request::is('admin/import*'))<li class="active">@else<li>@endif<a href="{{ url('admin') }}"><i class="icon-dashboard"></i><span>@lang('dashboard.dashboard')</span></a></li>
        @if(Request::is('admin/clients*'))<li class="active">@else<li>@endif<a href="{{ url('admin/clients') }}"><i class="icon-list-alt"></i><span>@lang('clients.clients')</span></a></li>
        @if(Request::is('admin/quotes*'))<li class="active">@else<li>@endif<a href="{{ url('admin/quotes') }}"><i class="icon-facetime-video"></i><span>@lang('quotes.quotes')</span></a></li>
        @if(Request::is('admin/transactions*'))<li class="active">@else<li>@endif<a href="{{ url('admin/transactions') }}"><i class="icon-bar-chart"></i><span>@lang('transactions.transactions')</span></a></li>
      </ul>
    </div>
  </div>
</div>
<div class="main">
  <div class="main-inner">
    <div class="container">
    @section('message')
      @if(Session::has('success_message'))
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        {{ Session::get('success_message') }}
      </div>
      @endif
      @if(Session::has('error_message'))
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        {{ Session::get('error_message') }}
      </div>
      @endif

      @if($errors->count())
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        @lang('messages.form.error')
        {{ HTML::ul($errors->all()) }}
      </div>
      @endif
    @show
		@yield('content')
    </div>
  </div>
</div>
<div class="footer">
  <div class="footer-inner">
    <div class="container">
      <div class="row">
        <div class="span12">{{ Config::get('page.footer') }}</div>
      </div>
    </div>
  </div>
</div>
{{ HTML::script('/js/jquery.js') }}
{{ HTML::script('/js/excanvas.min.js') }}
{{ HTML::script('/js/chart.min.js') }}
{{ HTML::script('/js/bootstrap.js') }}
{{ HTML::script('/js/bootstrap-datepicker.js') }}
{{ HTML::script('/js/full-calendar/fullcalendar.min.js') }}
{{ HTML::script('/js/selectize.js') }}
{{ HTML::script('/js/base.js') }}
@yield('footer')
</body>
</html>