app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::get('/', function(){
    if(Auth::check())
        return Redirect::to('/admin');
    else
        return Redirect::to('/login');
});

// Client
Route::any('/quotes/quote/{id}', 'QuotesController@quote');

// Admin login
Route::get('login', 'AuthController@index');
Route::post('login', 'AuthController@login');
Route::get('logout', 'AuthController@logout');

// Admin
Route::group(array('before' => 'auth'), function(){
    Route::group(array('prefix' => 'admin'), function(){
        Route::get('/', 'Admin\DashboardController@index');
        Route::post('/', 'Admin\DashboardController@history');
        Route::resource('/clients', 'Admin\ClientsController');
        Route::get('/quotes/mail/{id}', [
            'uses' => 'Admin\MailQuoteController@preview',
            'as'   => 'admin..quotes.mail'
        ]);
        Route::post('/quotes/mail/{id}', [
            'uses' => 'Admin\MailQuoteController@send',
            'as'   => 'admin..quotes.mail'
        ]);    Route::resource('/quotes', 'Admin\QuotesController');
        Route::get('/transactions', 'Admin\TransactionsController@index');
        Route::post('/import/quote', [
        	'uses' => 'Admin\ImportController@quote',
            'as' => 'admin..import.quote'
        ]);
        Route::get('/export', 'Admin\ExportController@index');
    });
});


// IPNs
Route::group(array('prefix' => 'ipn'), function(){
    Route::any('/webpay', 'IPN\WebpayController@notification');
});

app/models/Quote.php
<?php

use Illuminate\Database\Eloquent\ModelNotFoundException;

class Quote extends Eloquent{
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'quotes';

	// Custom attributes
	public function getPriceAttribute(){
		$price = 0;
		foreach($this->items as $item){
			$price += $item->price;
		}
		return $price;
	}

	public function getIvaPriceAttribute(){
		return round($this->price * 1.19);
	}

	public function getIsPaidAttribute(){
		return '0000-00-00 00:00:00' == $this->paid_at ? false : true;
	}

	// Model attributes
	public function items(){
		return $this->hasMany('QuoteItem');
	}

	public function transactions(){
		return $this->hasMany('Transaction');
	}

	public function client(){
		return $this->belongsTo('Client');
	}
	// General
	public static function findByCode($code){
		return self::where('code', $code)->first();
	}

	// Scopes
	public function scopeOfUnpaid($query){
		return $query->where('paid_at', '=', '0000-00-00 00:00:00');
	}

	public function scopeOfPaid($query){
		return $query->where('paid_at', '!=', '0000-00-00 00:00:00');
	}
}

app/controllers/QuotesController.php
<?php
use Illuminate\Support\Facades\View;

class QuotesController extends BaseController{
	public function quote($id){
		if($quote = Quote::findOrFail($id)){
			return View::make('client.quotes.quote', compact('quote'));
		}
	}
}

app/controllers/admin/QuoteController.php
<?php
namespace Admin;

use Quote, Client, QuoteItem;

use Validator, Input, Redirect, Session, Lang;

use Illuminate\Support\Facades\View;

use AdminController;
class QuotesController extends AdminController{
	public function index(){
		$quotes = Quote::all();
		return View::make('admin.quotes.index', compact('quotes'));
	}
	public function create(){
        $clients = Client::all();
		return View::make('admin.quotes.create', compact('clients'));
	}
	public function store(){
        $rules = array(
            'client_id'     => 'required',
            'name'          => 'required'
        );
        foreach(Input::get('quote_item') as $i => $quote_item){
            $rules['quote_item.' . $i . '.name']        = 'required';
            $rules['quote_item.' . $i . '.amount']      = 'required|numeric';
        }
        $validator = Validator::make(Input::all(), $rules);
        if ($validator->fails()) {
            return Redirect::to('admin/quotes/create')
                ->withErrors($validator)
                ->withInput(Input::except('password'));
        }
        else {
            $quote = new Quote;
            $quote->name 		= Input::get('name');
            $quote->description	= Input::get('description');
            $quote->client_id	= Input::get('client_id');
            $quote->save();
            foreach(Input::get('quote_item') as $quote_item){
                extract($quote_item);
                $quote_item = new QuoteItem;
                $quote_item->name        = $name;
                $quote_item->description = $description;
                $quote_item->amount      = $amount;
                $quote->items()->save($quote_item);
            }

            Session::flash('success_message', Lang::get('quotes.store.success'));
            return Redirect::to('admin/quotes');
        }
	}
    public function show($id){
        $quote = Quote::findOrFail($id);

        return View::make('admin.quotes.show', compact('quote'));
    }
	public function edit($id){
        $quote   = Quote::findOrFail($id);
        $clients = Client::all();

        return View::make('admin.quotes.edit', compact('quote', 'clients'));
    }
    public function update($id){
        $quote = Quote::findOrFail($id);
        #exit($id);
        $rules = array(
            'client_id'     => 'required',
            'name'          => 'required'
        );
        foreach(Input::get('quote_item') as $i => $item){
            if(!(empty($item['name']) and empty($item['description']) and empty($item['amount']))){
                $rules['quote_item.' . $i . '.name']        = 'required';
                $rules['quote_item.' . $i . '.amount']      = 'required|numeric';
            }
        }
        $validator = Validator::make(Input::all(), $rules);

        if ($validator->fails()) {
            return Redirect::route('admin..quotes.update', $id)
                ->withErrors($validator)
                ->withInput(Input::except('password'));
        }
        else {
            $quote->name        = Input::get('name');
            $quote->description = Input::get('description');
            $quote->client_id   = Input::get('client_id');
            $quote->save();
            foreach(Input::get('quote_item') as $item){
                if($quote_item = QuoteItem::findOrNew((@$item['id'] ? $item['id'] : false))){
                    if(empty($item['name']) and empty($item['description']) and empty($item['amount'])){
                        $quote_item->delete();
                    }
                    else{
                        $quote_item->name        = $item['name'];
                        $quote_item->description = $item['description'];
                        $quote_item->amount      = $item['amount'];
                        if($quote_item->quote_id)
                            $quote_item->save();
                        else
                          $quote->items()->save($quote_item);
                    }
                }
            }
            Session::flash('success_message', Lang::get('quotes.store.success'));

            return Redirect::route('admin..quotes.update', $id);
        }
    }
    public function destroy($id){
        $quote = Quote::findOrFail($id);
        $quote->delete();

        Session::flash('success_message', Lang::get('quotes.destroy.success'));

        return Redirect::to('admin/quotes');
    }
}

app/views/admin/quotes/create.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
	<div class="span12">
		<div class="widget">
			<div class="widget-header"> <i class="icon-th-list"></i>
				<h3>@lang('quotes.quotes')</h3>
			</div>
			<div class="widget-content">
				{{ Form::open(array('url' => 'admin/quotes', 'class' => 'form-horizontal')) }}
					<fieldset>
						<div class="control-group">
							{{ Form::label('name', trans('quotes.client'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::select('client_id', $clients->lists('fullname', 'id'), null, array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('name', trans('quotes.name'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::text('name', Input::old('name'), array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('surname', trans('quotes.description'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::textarea('description', Input::old('description'), array('class' => 'span6')) }}
							</div>
						</div>
						<div class="control-group">
							<div class="widget">
								<div class="widget-header">
									<h3>@lang('quotes.items')</h3>
									<a href="javascript:addQuoteItem()" class="btn btn-mini btn-default">@lang('form.button.add')</a>
								</div>
								<div class="widget-content">
									<div id="quote-items" class="accordion">
										@if(Request::old('quote_item'))
											@foreach(Request::old('quote_item') as $i => $quote_item)
											<div class="accordion-group">
												<div class="accordion-heading">
													<span class="accordion-toggle">
														<a class="btn btn-mini btn-default" onclick="javascript:removeThisQuoteItem(this)">@lang('form.button.remove')</a>
														<a href="#collapse{{ $i }}" data-toggle="collapse" data-parent="#quote-items">@if(!empty($quote_item['name'])) {{ $quote_item['name'] }} @else Item #{{ $i }} @endif</a>
													</span>
												</div>
											    <div id="collapse{{ $i }}" class="accordion-body collapse @if($i==1) in @endif">
													<div class="accordion-inner">
														<div class="control-group">
															{{ Form::label("quote_item[{$i}][name]", trans('quote_items.name'), array('class' => 'control-label')) }}
															<div class="controls">
																{{ Form::text("quote_item[{$i}][name]", $quote_item['name'], array('class' => 'span6')) }}
															</div>
														</div>
														<div class="control-group">
															{{ Form::label("quote_item[{$i}][description]", trans('quote_items.description'), array('class' => 'control-label')) }}
															<div class="controls">
																{{ Form::text("quote_item[{$i}][description]", $quote_item['description'], array('class' => 'span6')) }}
															</div>
														</div>
														<div class="control-group">
															{{ Form::label("quote_item[{$i}][amount]", trans('quote_items.amount'), array('class' => 'control-label')) }}
															<div class="controls">
																{{ Form::text("quote_item[{$i}][amount]", $quote_item['amount'], array('class' => 'span6')) }}
															</div>
														</div>
													</div>
												</div>
											</div>
											@endforeach
										@else
										<div class="accordion-group">
											<div class="accordion-heading">
												<span class="accordion-toggle">
													<a class="btn btn-mini btn-default" onclick="javascript:removeThisQuoteItem(this)">@lang('form.button.remove')</a>
													<a href="#collapse1" data-toggle="collapse" data-parent="#quote-items">Item #1</a>
												</span>
											</div>
										    <div id="collapse1" class="accordion-body collapse in">
												<div class="accordion-inner">
													<div class="control-group">
														{{ Form::label('quote_item[1][name]', trans('quote_items.name'), array('class' => 'control-label')) }}
														<div class="controls">
															{{ Form::text('quote_item[1][name]', null, array('class' => 'span6')) }}
														</div>
													</div>
													<div class="control-group">
														{{ Form::label('quote_item[1][description]', trans('quote_items.description'), array('class' => 'control-label')) }}
														<div class="controls">
															{{ Form::text('quote_item[1][description]', null, array('class' => 'span6')) }}
														</div>
													</div>
													<div class="control-group">
														{{ Form::label('quote_item[1][amount]', trans('quote_items.amount'), array('class' => 'control-label')) }}
														<div class="controls">
															{{ Form::text('quote_item[1][amount]', null, array('class' => 'span6')) }}
														</div>
													</div>
												</div>
											</div>
										</div>
										@endif
									</div>
								</div>
							</div>
						</div>
						<div class="control-group">
							{{ Form::label('total', trans('quotes.total'), array('class' => 'control-label')) }}
							<div class="controls">
								{{ Form::hidden('_total', Input::old('_total'), array('id' => '_total')) }}
								{{ Form::text('total', Input::old('_total'), array('class' => 'span6', 'id' => 'total')) }}
							</div>
						</div>
						<div class="form-actions">
							<button type="submit" class="btn btn-primary">@lang('form.button.save')</button>
							<button class="btn">@lang('form.button.cancel')</button>
						</div>
					</fieldset>
				{{ Form::close() }}
			</div>
		</div>
	</div>
</div>
@stop
@section('footer')
<script type="text/javascript">
	var quoteItemNumber = 2;
	$(document).ready(function(){
		$('select[name="client_id"]').selectize();
		$('input[name^="quote_item"]').each(function(i,element){
			if($(element).attr('name').indexOf('amount') >= 0){
				$(element).keyup(totalCalculation);
			}
			else if($(element).attr('name').indexOf('name') >= 0){
				$(element).keyup(changeThisTitle)
			}
		});
	});
	function totalCalculation(){
		total = 0;
		$('input[name^="quote_item"]').each(function(i,element){
			if($(element).attr('name').indexOf('amount') >= 0){
				amount = $(element).val();
				if(amount) total += parseInt(amount);
			}
		});
		$('#total, #_total').val(total);
	}
	function changeThisTitle(){	
		$('a', $(this).closest('.accordion-group').children()).next().html($(this).val());
	}
	function removeThisQuoteItem(element){
		$(element).closest('.accordion-group').remove();
	}
	function addQuoteItem(){
		$('#quote-items')
			.append(
			$('<div>')
				.addClass('accordion-group')
				.append(
				$('<div>')
					.addClass('accordion-heading')
					.append(
					$('<span>')
						.addClass('accordion-toggle')
						.append(
						$('<a>')
							.addClass('btn btn-mini btn-default')
							.html('@lang('form.button.remove')')
							.attr('onclick', 'javascript:removeThisQuoteItem(this)')
						)
						.append(' ')
						.append(
						$('<a>')
							.attr('id', '#collapseTitle' + quoteItemNumber)
							.attr('data-toggle', 'collapse')
							.attr('data-parent', '#quote-items')
							.attr('href', '#collapse' + quoteItemNumber)
							.html('Item #' + quoteItemNumber)
						)
					)
				)
				.append(
				$('<div>')
					.attr('id', 'collapse' + quoteItemNumber)
					.addClass('accordion-body collapse')
					.append(
					$('<div>')
						.addClass('accordion-inner')
						.append(
						$('<div>').addClass('control-group')
							.append(
							$('<label>')
								.addClass('control-label')
								.attr('for', 'quote_item['+quoteItemNumber+'][name]')
								.html('@lang('quote_items.name')')
							)
							.append(
							$('<div>')
								.addClass('controls')
								.append(
								$('<input>')
									.addClass('span6')
									.attr('name', 'quote_item['+quoteItemNumber+'][name]')
									.keyup(changeThisTitle)
								)
							)
						)
						.append(
						$('<div>').addClass('control-group')
							.append(
							$('<label>')
								.addClass('control-label')
								.attr('for', 'quote_item['+quoteItemNumber+'][description]')
								.html('@lang('quote_items.description')')
							)
							.append(
							$('<div>')
								.addClass('controls')
								.append(
								$('<input>')
									.addClass('span6')
									.attr('name', 'quote_item['+quoteItemNumber+'][description]')
								)
							)
						)
						.append(
						$('<div>').addClass('control-group')
							.append(
							$('<label>')
								.addClass('control-label')
								.attr('for', 'quote_item['+quoteItemNumber+'][amount]')
								.html('@lang('quote_items.amount')')
							)
							.append(
							$('<div>')
								.addClass('controls')
								.append(
								$('<input>')
									.addClass('span6')
									.attr('name', 'quote_item['+quoteItemNumber+'][amount]')
									.keyup(totalCalculation)
								)
							)
						)
					)
				)
			);
		quoteItemNumber++;
	}
</script>
@stop

app/views/admin/quotes/index.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
	<div class="span12">
		<div class="widget widget-table action-table">
			<div class="widget-header">
				<i class="icon-th-list"></i>
				<h3>@lang('quotes.quotes')</h3>
				<!-- <a href="{{ url('admin/quotes/create') }}" class="btn btn-mini btn-default">Agregar</a>-->
			</div>
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>@lang('quotes.id')</th>
							<th>@lang('quotes.name')</th>
							<th>@lang('quotes.client')</th>
							<th>@lang('quotes.created_at')</th>
							<!--<th></th>-->
						</tr>
					</thead>
					<tbody>
						@foreach($quotes as $quote)
						<tr>
							<td><a href="{{ URL::route('admin..quotes.show', $quote->id) }}">{{ $quote->id }}</a></td>
							<td><a href="{{ URL::route('admin..quotes.show', $quote->id) }}">{{ $quote->name }}</a></td>
							<td>{{ $quote->client->fullname }}</td>
							<td>{{ $quote->created_at }}</td>
							<!--<td>
								<a href="{{ url("admin/quotes/{$quote->id}/edit") }}" class="btn btn-mini btn-success pull-left">@lang('form.button.edit') <i class="btn-icon-only icon-ok"> </i></a>
							    {{ Form::open(array('url' => array('admin/quotes', $quote->id), 'method' => 'delete', 'class' => 'pull-left', 'style' => 'margin: 0 0 0 5px')) }}
								<buttom type="submit" class="btn btn-danger btn-mini">@lang('form.button.remove') <i class="btn-icon-only icon-remove"> </i></button>
								{{ Form::close() }}
							</td>-->
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@stop

app/views/admin/quotes/mail.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
	<div class="span12">
		<div class="widget">
			<div class="widget-header">
				<i class="icon-th-list"></i>
				<h3>{{ $quote->client->name }}</h3>
			</div>
			<div class="widget-content">
				{{ Form::open([
					'route' => ['admin..quotes.mail', $quote->id],
					'class' => 'form-horizontal'
				]) }}
				<h3 class="pull-right">@lang('quotes.mail.title', ['code' => $quote->code])</h3>
				<div class="clearfix"></div>
				<hr />
				<fieldset>
					<table class="table table-bordered table-condensed">
						<thead>							<tr>
								<th>@lang('quotes.code')</th>
								<th>@lang('quotes.description')</th>
								<th>@lang('quotes.quantity')</th>
								<th>@lang('quotes.unit_price')</th>
								<th>@lang('quotes.price')</th>
							</tr>
						</thead>
						<tbody>
							@foreach($quote->items as $item)
							<tr>
								<td>{{ $item->code }}</td>
								<td>{{ $item->description }}</td>
								<td>{{ $item->quantity }}</td>
								<td>{{ $item->unit_price }}</td>
								<td>{{ $item->price }}</td>
							</tr>
							@endforeach
						</tbody>
						<tfoot>
							<tr>
								<td colspan="4" align="right">@lang('quotes.total')</td>
								<td>{{ $quote->price }}</td>
							</tr>
							<tr>
								<td colspan="4" align="right">@lang('quotes.iva_total')</td>
								<td>{{ $quote->iva_price }}</td>
							</tr>
						</tfoot>
					</table>
					<div class="form-actions" align="right">
						@if(empty($quote->client->email))
						<input name="email" id="email" placeholder="@lang('clients.email')" />
						@else
						<input name="email" id="email" type="hidden" placeholder="@lang('clients.email')" value="{{ $quote->client->email }}" />
						@endif
						<button class="btn">@lang('form.button.cancel')</button>
						<button type="submit" class="btn btn-primary">@lang('form.button.send')</button>
					</div>
				</fieldset>
				{{ Form::close() }}
			</div>
		</div>
	</div>
</div>
@stop

app/views/admin/quotes/show.blade.php
@extends('admin.layout')
@section('content')
<div class="row">
	<div class="span5">
		<div class="widget widget-table action-table">
			<div class="widget-header"> <i class="icon-th-list"></i>
					<h3>
					@if($quote->is_paid)
					<span class="label label-success">@lang('quotes.paid')</span>
					@else
					<span class="label label-danger">@lang('quotes.nonpaid')</span>
					@endif
					{{ $quote->name }}
				</h3>
				<!-- <a href="{{ url("admin/quotes/{$quote->id}/edit") }}" class="btn btn-mini btn-default">@lang('form.button.edit')</a> -->
			</div>
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<tr>
						<td width="35%">@lang('quotes.name')</td>
						<td>{{ $quote->name }}</td>
					</tr>
					<tr>
						<td>@lang('quotes.description')</td>
						<td>{{ $quote->description }}</td>
					</tr>
					@if($quote->sent_to)
					<tr>
						<td>@lang('quotes.sent_to')</td>
						<td>{{ $quote->sent_to }}</td>
					</tr>
					@endif
					@if($quote->sent_at)
					<tr>
						<td>@lang('quotes.sent_at')</td>
						<td>{{ $quote->sent_at }}</td>
					</tr>
					@endif
					@if($quote->paid_at)
					<tr>
						<td>@lang('quotes.paid_at')</td>
						<td>{{ $quote->paid_at }}</td>
					</tr>
					@endif
					<tr>
						<td>@lang('quotes.created_at')</td>
						<td>{{ $quote->created_at }}</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="widget widget-table action-table">
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<tr>
						<td width="35%">@lang('clients.fullname')</td>
						<td>{{ $quote->client->fullname }}</td>
					</tr>
					<tr>
						<td>@lang('clients.rut')</td>
						<td>{{ $quote->client->rut }}</td>
					</tr>
					<tr>
						<td>@lang('clients.email')</td>
						<td>{{ $quote->client->email }}</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="widget widget-table action-table">
			<div class="widget-header">
				<i class="icon-th-list"></i>
				<h3>@lang('transactions.last')</h3>
			</div>
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<thead>
						<th>@lang('transactions.id')</th>
						<th>@lang('transactions.quote')</th>
						<th>@lang('transactions.date')</th>
						<th>@lang('transactions.gateway')</th>
						<th>@lang('transactions.amount')</th>
					</thead>
					<tbody>
						@foreach($quote->transactions->take(10) as $transaction)
						<tr>
							<td>{{ $transaction->id }}</td>
							<td>{{ $transaction->quote->name }}</td>
							<td>{{ $transaction->paid_at }}</td>
							<td>{{ $transaction->gateway }}</td>
							<td>{{ $transaction->amount }}</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="span7">
		<div class="widget widget-table action-table">
			<div class="widget-header">
				<i class="icon-th-list"></i>
				<h3>@lang('quote_items.quote_items')</h3>
			</div>
			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<thead>
						<th>@lang('quote_items.name')</th>
						<th>@lang('quote_items.description')</th>
						<th>@lang('quote_items.unit_price')</th>
						<th>@lang('quote_items.quantity')</th>
						<th>@lang('quote_items.amount')</th>
					</thead>
					<tbody>
						@foreach($quote->items as $item)
						<tr>
							<td>{{ $item->name }}</td>
							<td>{{ $item->description }}</td>
							<td>{{ $item->unit_price }}</td>
							<td>{{ $item->quantity }}</td>
							<td>{{ $item->price }}</td>
						</tr>
						@endforeach
					</tbody>
					<tfooter>
						<tr>
							<td colspan="4">@lang('quotes.total')</td>
							<td>{{ $quote->price }}</td>
						</tr>
					</tfooter>
				</table>
			</div>
		</div>
	</div>
</div>
@stop